# Generated by Django 5.1.4 on 2024-12-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('Effect', models.CharField(max_length=10)),
            ],
        ),
    ]
