# Generated by Django 5.1.4 on 2024-12-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='Effect',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
